Repository Hekili/hekili, pull requests merged in 2024-09, with the labels that each got.

#3683 Arcane, Ret, Shadow
  TheWarWithin/MageArcane.lua
  TheWarWithin/PaladinRetribution.lua
  TheWarWithin/PriestShadow.lua
  TheWarWithin/Priorities/MageArcane.simc
  TheWarWithin/Priorities/PriestShadow.simc
Labels: recommendation, Pending PR

#3718 fixed a lifebloom, which can not be founded in Keybinds
  TheWarWithin/DruidRestoration.lua
Labels: recommendation, TacoDog

#3733 Arcane, BM
  TheWarWithin/HunterBeastMastery.lua
  TheWarWithin/MageArcane.lua
  TheWarWithin/Priorities/MageArcane.simc
Labels: recommendation, retail, TacoDog

#3738 Hunter Spec Option: Mend Pet
  TheWarWithin/HunterBeastMastery.lua
  TheWarWithin/HunterMarksmanship.lua
  TheWarWithin/HunterSurvival.lua
  TheWarWithin/Priorities/HunterBeastMastery.simc
  TheWarWithin/Priorities/HunterMarksmanship.simc
  TheWarWithin/Priorities/HunterSurvival.simc
Labels: enhancement, retail, TacoDog

#3754 Resto Shaman Down[our
  TheWarWithin/ShamanRestoration.lua
Labels: TacoDog
