Repository Hekili/hekili, pull requests merged in 2025-03, with the labels that each got.

#4565 Shaman tier set IDs
  TheWarWithin/ShamanElemental.lua
  TheWarWithin/ShamanEnhancement.lua
  TheWarWithin/ShamanRestoration.lua
Labels: bug

#4561 DH: Remove all references to the temporary inertia names
  TheWarWithin/DemonHunterHavoc.lua
Labels: bug

#4563 Resto Druid should use their own pack string. Leave Feral alone.
  TheWarWithin/DruidRestoration.lua
Labels: bug

#4564 Updated Snapshot Formatting
  Core.lua
  Hekili.lua
  Options.lua
Labels: enhancement

#4587 arms tier set ID
  TheWarWithin/WarriorArms.lua
Labels: bug

#4584 Probably trigger solar eclipses
  TheWarWithin/DruidBalance.lua
Labels: bug

#4567 Add plural gear registration option
  Classes.lua
  TheWarWithin/ShamanEnhancement.lua
Labels: enhancement

#4604 WW Settings
  TheWarWithin/MonkWindwalker.lua
Labels: enhancement

#4636 Intuition spellID
  TheWarWithin/MageArcane.lua
Labels: bug

#4642 Default Empowerment
  Core.lua
  TheWarWithin/MonkWindwalker.lua
Labels: enhancement

#4650 Unholy APL Fix
  TheWarWithin/DeathKnightUnholy.lua
  TheWarWithin/Priorities/DeathKnightUnholy.simc
Labels: bug

#4664 Fix wrong WW Crackling Jade Lighting toggle
  TheWarWithin/MonkWindwalker.lua
Labels: bug

#4663 Marksman APL
  TheWarWithin/HunterMarksmanship.lua
  TheWarWithin/Priorities/HunterMarksmanship.simc
Labels: SimC APL Sync

#4662 Devastation APL
  TheWarWithin/EvokerDevastation.lua
  TheWarWithin/Priorities/EvokerDevastation.simc
Labels: SimC APL Sync

#4661 Boomkin APL + minor tweak to fury of elune
  TheWarWithin/DruidBalance.lua
  TheWarWithin/Priorities/DruidBalance.simc
Labels: SimC APL Sync

#4660 Sin Rogue APL
  TheWarWithin/Priorities/RogueAssassination.simc
  TheWarWithin/RogueAssassination.lua
Labels: SimC APL Sync

#4658 Fix Unfurling darkness again (again [again] )
  State.lua
  TheWarWithin/PriestShadow.lua
Labels: bug

#4647 Per-Ability DoT cap setting
  Classes.lua
  Options.lua
  State.lua
Labels: enhancement

#4638 Anti-shoot-self-in-foot-feature
  Options.lua
Labels: enhancement
