Repository Hekili/hekili, pull requests merged in 2025-01, with the labels that each got.

#4289 Feral, Balance, Disc Priest
  TheWarWithin/DruidBalance.lua
  TheWarWithin/DruidFeral.lua
  TheWarWithin/PriestDiscipline.lua
Labels: retail, 🔝 escalated

#4316 Fix Typo in Vengeance SIMC file
  TheWarWithin/DemonHunterVengeance.lua
  TheWarWithin/Priorities/DemonHunterVengeance.simc
Labels: 🔝 escalated

#4314 Cataclysm: Mage Profile Update
  Cataclysm/APLs/MageFrost.simc
  Cataclysm/Mage.lua
Labels: classic, 🔝 escalated

#4286 Chat Commands
  Options.lua
Labels: retail, 🔝 escalated

#4283 #4264 - Unholy: Primary - Death Coil Auto Pop (Align Runes + RP with Frost
  TheWarWithin/DeathKnightUnholy.lua
Labels: retail, 🔝 escalated

#4279 demonology: add missing felstorm ability
  TheWarWithin/WarlockDemonology.lua
Labels: retail, 🔝 escalated
